[package]
name = "clap-config-file-core"
version = "0.1.0"
description = "Core library for clap-config-file"
license = "MIT"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
clap = { version = "4.0", features = ["derive"] }
serde_yaml = "0.9" 